name: lelinting, testing, building
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pipeLine:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.JS ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: instal modules
        run: npm install
      - name: build production project
        run: npm run build:prod
      - name: unit test
        run: npm run unit
